### PR TITLE
Adds Location Information in Dashboard

### PR DESCRIPTION
**Pull request by arjungrylls**
# Dashboard Revamp

Adds Location information in dashboard and in add job form.  Uses Button Group for Priority in add job form

contributes to #22 

Screenshot from 2020-07-02 13-42-19

### CODE REVIEW

**Comment by koushikmohan1996** [comment]
@arjungrylls What will happen on clicking a button group? Can you share a gif?

**Comment by koushikmohan1996** [comment]
Also E2E tests are failed due to change in modal box

**Comment by saw-jan** [comment]
e2e tests fails because of change in UI. so can ignore travis build fail for now.

**Comment by arjungrylls** [comment]
UI after handling the selected button colour. 
Screenshot from 2020-07-03 12-20-08

**Comment by koushikmohan1996** [comment]
Need to make E2E test changes

**Pull request merged**
