### PR TITLE
Add signup and login acceptance test using codecept js

### PR DESCRIPTION
**Pull request by HariBhandari07**
## Description
This PR adds signup and login acceptance tests using codecept js

Fixes # (issue)

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## How Has This Been Tested

Please describe the tests that you ran to verify your changes. Provide instructions so we can reproduce. Please also list any relevant details for your test configuration

- [ ] Unit Test
- [ ] Integration Test

## Checklist

- [ ] My code follows the style guidelines of this project
- [ ] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] I have made corresponding changes to the documentation
- [ ] My changes generate no new warnings
- [ ] I have added tests that prove my fix is effective or that my feature works
- [ ] New and existing unit tests pass locally with my changes
- [ ] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by koushikmohan1996** [comment]
@HariBhandari07  Thank you so much. I will add this to CI also

**Comment by koushikmohan1996** [comment]
@all-contributors add @HariBhandari07 for code and test

**Comment by HariBhandari07** [comment]
@koushikmohan1996 This PR needs some optimization. I was just checking out codecept js because of your suggestion. Since this PR is already merged I will work on the optimization in the next PR :)

**Comment by koushikmohan1996** [comment]
@HariBhandari07 Sure no problem. Sorry, I thought the PR is complete. 
Next time please make a draft PR/ add WIP in the title. 

Thanks for your contribution :)

**Comment by koushikmohan1996** [comment]
@HariBhandari07 BTW provided access to this repo so you can directly create branches and no need to update your fork.

**Comment by individual-it** [comment]
does this fix #14 ?

**Comment by koushikmohan1996** [comment]
@individual-it This is E2E test. When I created that issue. I had basic dom testing in my mind. I think I will wait for @JesusELuna  to come up with dom testing

**Pull request merged**
