### PR TITLE
[LandingPage]: Improve typography and Landing Page

### LINKED ISSUE #61: [LandingPage]: Improve Typography
- Typography is consistent throughout the project.
- This issue is regarding only LandingPage.

### PR DESCRIPTION
**Pull request by hiteshkundal**
## Description

- [x] Improve Typography on LandingPage.
- [x] Move CSS style rules from separate SCSS files to JS files.
- [x] Start promoting CSS in JS now onwards.
- [x] Take advantage of the Material-UI design system.

Fixes #61 

## feat

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hiteshkundal** [comment]
ezgif com-video-to-gif

**Comment by hiteshkundal** [comment]
> Are we going to use CSS in JS instead of separate file hereafter? If yes What is the exact reason? Just curious


Since we are using Material-UI, they have an established design system that provides consistency throughout. To take full advantage of their design system, CSS in JS works the best. Material-UI is already using CSS in JS internally.
For example, 
```
const useStyles = makeStyles(theme => ({
    root: {
        margin: theme.spacing(2),
        letterSpacing: theme.spacing(0.1)
    },
}));

const Types = (props) => {
    const classes = useStyles();
    const {
        children, variant, component, color, align, style, className
    } = props;

    return (
        <Typography
            className={clsx(classes.root, className)}
            variant={variant}
            component={component}
            color={color}
            align={align}
            style={style}
        >
            {children}
        </Typography>
    );
};
```

We are creating common styles from makeStyles API -> will apply to all instances of this component. But also we are receiving className as props which are the custom style for some particular instances of this component. Here, we combine these and apply altogether as single className.
With CSS in JS, we can take advantage of the global theme as well.
Not only consistency, but we can reuse components much better than earlier.

**Comment by hiteshkundal** [comment]
> Are we going to use CSS in JS instead of separate file hereafter? If yes What is the exact reason? Just curious

This talks can help you to understand better what I am trying to say-
https://www.youtube.com/watch?v=js9BihmW9ak&t=1327s

**Comment by koushikmohan1996** [comment]
Thanks :)

**Pull request merged**
