### PR TITLE
[Feature]: Add sass

### LINKED ISSUE #52: Add SCSS
We are going forward with SCSS and all CSS should be changed to SCCS.

### PR DESCRIPTION
**Pull request by hiteshkundal**
# Pull Request Template

## Description
- [x] Add sass support for the project.
- [x] Improve some components.

Fixes #52 #29 

## feat

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

## Checklist

- [x] My code follows the style guidelines of this project
- [x] I have performed a self-review of my own code
- [x] I have commented on my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes
- [x] Any dependent changes have been merged and published in downstream modules

### CODE REVIEW

**Comment by hiteshkundal** [comment]
add-sass

**Comment by hiteshkundal** [comment]
> I think you should update your branch. 2 days back I moved AccountDetails, and other components to container folder a it is not a component and will not be reused

My branch is up to date with the master. I kept the AccountDetails in component because it does not contain any state or business logic. For the reusable components, we will create another folder called UI inside components in the near future which will consist of only re-usable UI like loader, etc.
Containers -> must have a state that matters to business logic
Component -> does not contain a state that matters to business logic or outside the component.

**Comment by koushikmohan1996** [comment]
> > I think you should update your branch. 2 days back I moved AccountDetails, and other components to container folder a it is not a component and will not be reused
> 
> My branch is up to date with the master. I kept the AccountDetails in component because it does not contain any state or business logic. For the reusable components, we will create another folder called UI inside components in the near future which will consist of only re-usable UI like loader, etc.
> Containers -> must have a state that matters to business logic
> Component -> does not contain a state that matters to business logic or outside the component.

Won't it increase the complexity of this very simple project? Sure, I get your point. But I think it is too complicated this simple project as folders are kept on increasing.

The way I see it.
Components > Reusable block of code
Container > Combination of many components eventually to make page or screen

**Comment by koushikmohan1996** [comment]
Also I don't think it will be easy to segregate based on the state. As If I introduce state in any of component I have to move it to container and I should keep track of it.

**Comment by hiteshkundal** [comment]
> > > I think you should update your branch. 2 days back I moved AccountDetails, and other components to container folder a it is not a component and will not be reused
> > 
> > 
> > My branch is up to date with the master. I kept the AccountDetails in component because it does not contain any state or business logic. For the reusable components, we will create another folder called UI inside components in the near future which will consist of only re-usable UI like loader, etc.
> > Containers -> must have a state that matters to business logic
> > Component -> does not contain a state that matters to business logic or outside the component.
> 
> Won't it increase the complexity of this very simple project? Sure, I get your point. But I think it is too complicated this simple project as folders are kept on increasing.
> 
> The way I see it.
> Components > Reusable block of code
> Container > Combination of many components eventually to make page or screen


As hese articles mention 
https://medium.com/@dan_abramov/smart-and-dumb-components-7ca2f9a7c7d0
https://hackernoon.com/structuring-projects-and-naming-components-in-react-1261b6e18d76
1.  I think the one of the reasons for using React is to create components so small (as well as reusable) so that it is easy to focus and extend that. React never says that we should not create more folders and files. I think more is better to focus on. This approach will help in the long-term.
2. If you see our components folder, there will be absolutely no component that is reusable right now. The reusability of components is something that we thrive to achieve over time. So, we can not segregate these two based on the only reusability.
3. I am not segregating these two based on state. I am segregating based on critical business logic. 
Component -> reusable or maintain state only for UI, not for critical logic.
Containers -> contains a state that is very critical to business logic. 
The whole idea is to separate the worry(critical logic) and style or UI differently. Fewer items in the container -> few worries. 
I know react-hooks make it difficult to segregate these two. Earlier, all class-based components used to be in containers and all functional components used to be in the components folder.

**Comment by hiteshkundal** [comment]
Screenshot 2020-03-16 at 7 30 39 PM

**Comment by koushikmohan1996** [comment]
Thanks :)

**Pull request merged**
